[package]
name = "gooseattack"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
debug = true

[dependencies]
goose = "0.17.2"
goose-eggs = "0.5.1"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
